FROM sbtscala/scala-sbt:eclipse-temurin-25.0.1_8_1.12.11_3.8.3 as builder

WORKDIR /app
COPY . .

ENV MAIN_CLASS=io.github.nicolasfara.es01.cluster.simple.App
RUN sbt "set cluster / assembly / mainClass := Some(\"$MAIN_CLASS\")" "cluster / assembly"

FROM eclipse-temurin:25.0.3_9-jre

WORKDIR /app
COPY --from=builder /app/cluster/target/cluster.jar /app/cluster.jar

ENTRYPOINT ["java", "-jar", "cluster.jar"]
