pekko {
  actor {
    provider = "cluster"
    serialization-bindings {
      "io.github.nicolasfara.es01.cluster.CborSerializable" = jackson-cbor
    }
  }
  remote.artery {
    canonical {
      hostname = "127.0.0.1"
    #   port = ??? Set dynamically in code
    }
  }

  cluster {
    seed-nodes = [
      "pekko://ClusterSystem@127.0.0.1:2551",
      "pekko://ClusterSystem@127.0.0.1:2552"]
  }
}