name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, macos-14, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: nicolasfara/build-check-deploy-sbt-action@1.0.44
        with:
          should-run-codecov: ${{ runner.os == 'Linux' }}
          check-command: sbt +scalafmtCheckAll +scalafmtSbtCheck '+scalafixAll --check' +test
          should-deploy: false
          maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  success:
    runs-on: ubuntu-24.04
    needs:
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
